apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-config
data:
  config: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80