apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-config
data:
  config: |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: example-app
    spec:
      source:
        repoURL: https://github.com/argoproj/argo-cd
        targetRevision: HEAD
        path: examples/guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      project: default